name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.7+9

environment:
  sdk: '>=3.6.0'

dependencies:
  flutter: { sdk: flutter }

  # Communication
  mqtt5_client: 4.11.0

  # Models
  freezed_annotation: 3.0.0
  json_annotation: 4.9.0
  fast_immutable_collections: 11.0.4

  # Rust bridge
  flutter_rust_bridge: 2.9.0
  rust_lib_momentoboothcompanionapp: { path: rust_builder }

  # UI
  widgetbook: 3.13.0
  widgetbook_annotation: 3.4.0
  mobx: 2.5.0
  flutter_mobx: 2.3.0
  go_router: 15.0.0
  fluent_ui: 4.11.3
  lottie: 3.3.1
  window_manager: 0.4.3

  # l10n
  flutter_localizations: { sdk: flutter }
  intl: any

  # Misc
  get_it: 8.0.3
  synchronized: 3.3.1
  talker: 4.7.2
  meta: any

dev_dependencies:
  # Code quality
  flutter_lints: 5.0.0
  integration_test: { sdk: flutter }

  # Models
  freezed: 3.0.0-0.0.dev
  json_serializable: 6.9.0
  build_runner: 2.4.15

  # UI
  widgetbook_generator: 3.12.0
  mobx_codegen: 2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
