name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.7+9

environment:
  sdk: '>=3.6.0'

dependencies:
  flutter: { sdk: flutter }

  # Communication
  mqtt5_client: 4.13.2

  # Models
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  fast_immutable_collections: 11.0.4

  # Rust bridge
  flutter_rust_bridge: 2.11.1
  rust_lib_momentoboothcompanionapp: { path: rust_builder }

  # UI
  widgetbook: 3.15.0
  widgetbook_annotation: 3.6.0
  mobx: 2.5.0
  flutter_mobx: 2.3.0
  go_router: 16.0.0
  fluent_ui: 4.12.0
  lottie: 3.3.1
  window_manager: 0.5.1

  # l10n
  flutter_localizations: { sdk: flutter }
  intl: any

  # Misc
  get_it: 8.2.0
  synchronized: 3.4.0
  talker: 4.9.3
  meta: any

dev_dependencies:
  # Code quality
  flutter_lints: 6.0.0
  integration_test: { sdk: flutter }

  # Models
  freezed: 2.5.7
  json_serializable: 6.9.0
  build_runner: 2.5.4

  # UI
  widgetbook_generator: 3.14.0
  mobx_codegen: 2.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
