name: momentoboothcompanionapp
description: A new Flutter project.

publish_to: 'none'

version: 0.0.7+9

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }

  # Communication
  mqtt5_client: 4.5.3

  # Models
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  fast_immutable_collections: 11.0.0

  # Rust bridge
  flutter_rust_bridge: 2.6.0
  rust_lib_momentoboothcompanionapp: { path: rust_builder }

  # UI
  widgetbook: 3.10.0
  widgetbook_annotation: 3.2.0
  mobx: 2.4.0
  flutter_mobx: 2.2.1+1
  go_router: 14.6.1
  fluent_ui: 4.9.2
  lottie: 3.1.3
  window_manager: 0.4.3

  # l10n
  flutter_localizations: { sdk: flutter }
  intl: any

  # Misc
  get_it: 8.0.2
  synchronized: 3.3.0+3
  talker: 4.5.1
  meta: any

dev_dependencies:
  # Code quality
  flutter_lints: 5.0.0
  integration_test: { sdk: flutter }

  # Models
  freezed: 2.5.7
  json_serializable: 6.9.0
  build_runner: 2.4.13

  # UI
  widgetbook_generator: 3.9.0
  mobx_codegen: 2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
