fastlane_require 'dotenv'

lane :ci_install_ios_appstore_cert_using_api do
  app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
    key_content: ENV['APP_STORE_CONNECT_KEY'],
    is_key_content_base64: true,
    in_house: false
  )

  setup_ci
  match(type: "appstore", readonly: true)
end

lane :ci_upload_to_testflight do |options|
  api_key = app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
    key_content: ENV['APP_STORE_CONNECT_KEY'],
    is_key_content_base64: true,
    in_house: false
  )

  upload_to_testflight(
    ipa: options[:ipa_path],
    skip_waiting_for_build_processing: true
  )
end

lane :ci_upload_to_play_store do |options|
  upload_to_play_store(
    package_name: 'com.momentobooth.companion',
    json_key_data: ENV['GOOGLE_SERVICE_ACCOUNT_KEY'],
    aab: options[:aab_path],
    track: 'internal',
    release_status: 'draft'
  )
end
