fastlane_require 'dotenv'

lane :ci_install_ios_appstore_cert_using_api do
  app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
    key_content: ENV['APP_STORE_CONNECT_KEY'],
    is_key_content_base64: true,
    in_house: false
  )

  setup_ci
  match(type: "appstore", readonly: true)
end

lane :ci_build_and_upload_to_testflight do
  api_key = app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
    key_content: ENV['APP_STORE_CONNECT_KEY'],
    is_key_content_base64: true,
    in_house: false
  )

  upload_to_testflight(
    ipa: 'build/ios/ipa/MB Companion.ipa',
    skip_waiting_for_build_processing: true
  )
end
